version: '3.7'

services:

  # ecommerce.products.api:
  #   container_name: ecommerce_products
  #   image: ${DOCKER_REGISTRY-}ecommerceproductsapi
  #   build:
  #     context: .
  #     dockerfile: eCommerce.Products.API/Dockerfile

  pgAdmin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=darko@dev.com
      - PGADMIN_DEFAULT_PASSWORD=adm1n
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - ecommerce
    ports:
      - "5050:80"
    restart: unless-stopped

  database:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adm1n
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ecommerce
    restart: unless-stopped

  redis:
    container_name: redis_cache
    image: redis:6-alpine
    command: /bin/sh -c "redis-server --requirepass ^9T~kDqF"
    ports:
      - "6379:6379"
    networks:
      - ecommerce
    restart: unless-stopped
    volumes:
      - cache:/data

  seq:
    container_name: seq_logging
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - ecommerce

  ecommerceproducts:
    container_name: ecommerceproducts
    build:
      network: host
      context: ../eCommerce.Products
      dockerfile: ./eCommerce.Products.API/Dockerfile
    ports:
      - "7099:443"
      - "5102:80"
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge

volumes:
  pgadmin-data:
  postgres:
  cache:
    driver: local